template header
minScore
maxScore
modifier

package templates

import com.sbnz.crcalculator.facts.Monster;

template "ability-modifiers"

	rule "Determine modifier for Strength @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(strength.abilityScore >= @{minScore} && strength.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Strength @{minScore}-@{maxScore} fired");
		modify ($m){ getStrength().setAbilityModifier(@{modifier}) };
	end
	
	rule "Determine modifier for Dexterity @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(dexterity.abilityScore >= @{minScore} && dexterity.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Dexterity @{minScore}-@{maxScore} fired");
		modify ($m){ getDexterity().setAbilityModifier(@{modifier}) };
	end
	
	rule "Determine modifier for Constitution @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(constitution.abilityScore >= @{minScore} && constitution.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Constitution @{minScore}-@{maxScore} fired");
		modify ($m){ getConstitution().setAbilityModifier(@{modifier}) };
	end
	
	rule "Determine modifier for Intelligence @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(intelligence.abilityScore >= @{minScore} && intelligence.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Intelligence @{minScore}-@{maxScore} fired");
		modify ($m){ getIntelligence().setAbilityModifier(@{modifier}) };
	end
	
	rule "Determine modifier for Wisdom @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(wisdom.abilityScore >= @{minScore} && wisdom.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Wisdom @{minScore}-@{maxScore} fired");
		modify ($m){ getWisdom().setAbilityModifier(@{modifier}) };
	end
	
	rule "Determine modifier for Charisma @{minScore}-@{maxScore}"
	lock-on-active
	when
		$m: Monster(charisma.abilityScore >= @{minScore} && charisma.abilityScore <= @{maxScore})
	then
		System.out.println("Determine modifier for Charisma @{minScore}-@{maxScore} fired");
		modify ($m){ getCharisma().setAbilityModifier(@{modifier}) };
	end

end template