package rules

import com.sbnz.crcalculator.facts.Monster;
import com.sbnz.crcalculator.facts.Action;
import com.sbnz.crcalculator.facts.Attack;

rule "Action processed"

    when
        $m: Monster($actions: actions)
		$action: Action($attacks: attacks, !processed) from $actions
		forall(Attack(attackBonus != null, damageBonus != null) from $attacks)
    then
        System.out.println("Action processed fired");
        $action.setProcessed(true);
        modify($m){setActions($actions)};

end