package rules

import com.sbnz.crcalculator.events.CalculationEvent;

declare ThreeConsecutiveMiscalculations
	@role(event)
end

rule "Three consecutive miscalculations"
agenda-group "messages"
	when
		Number(intValue == 3) from accumulate(
			$c: CalculationEvent(monster.expectedChallengeRating.ordinal != monster.challengeRating.ordinal)
		 	over window:length(3),
		 	count($c)
		 )
	then
		System.out.println("Three consecutive miscalculations fired");
		insert(new ThreeConsecutiveMiscalculations());
end