package rules

import com.sbnz.crcalculator.facts.Monster;
import com.sbnz.crcalculator.facts.Action;
import com.sbnz.crcalculator.facts.Attack;

rule "Determine strength damage bonus"

    when
        $m: Monster($actions: actions, $s: strength.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility.name().equalsIgnoreCase("STRENGTH"), damageBonus == null) from $attacks
    then
        System.out.println("Determine strength damage bonus fired");
        $attack.setDamageBonus($s);
        modify ($m) { setActions($actions) };
        
end

rule "Determine dexterity damage bonus"

    when
        $m: Monster($actions: actions, $d: dexterity.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility.name().equalsIgnoreCase("DEXTERITY"), damageBonus == null) from $attacks
    then
        System.out.println("Determine dexterity damage bonus fired");
        $attack.setDamageBonus($d);
        modify ($m) { setActions($actions) };

end