package rules

import com.sbnz.crcalculator.facts.Monster;

rule "Calculate average hit points"
    when
        $m: Monster($c: constitution.abilityModifier != null && hitDie != null && $r: hitDie.averageRoll != null && $n: numberOfHitDice != null && averageHitPoints == null)
    then
    	modify ($m) { setAverageHitPoints((int) ($n * ($r + $c)))};
        System.out.println("Average hit points calculated to " + $m.getAverageHitPoints());

end