package rules

import com.sbnz.crcalculator.facts.Monster;
import com.sbnz.crcalculator.facts.Action;
import com.sbnz.crcalculator.facts.Attack;
import com.sbnz.crcalculator.facts.AbilityName;
import com.sbnz.crcalculator.facts.AttackType;

rule "Determine strength damage bonus"

    when
        $m: Monster($actions: actions, strength.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.STRENGTH, damageBonus == null, type == AttackType.ATTACK_ROLL) from $attacks
    then
        System.out.println("Determine strength damage bonus fired");
        $attack.setDamageBonus($m.getStrength().getAbilityModifier());
        modify ($m) { setActions($actions) };
        
end

rule "Determine dexterity damage bonus"

    when
        $m: Monster($actions: actions, dexterity.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.DEXTERITY, damageBonus == null, type == AttackType.ATTACK_ROLL) from $attacks
    then
        System.out.println("Determine dexterity damage bonus fired");
        $attack.setDamageBonus($m.getDexterity().getAbilityModifier());
        modify ($m) { setActions($actions) };

end