package rules

import com.sbnz.crcalculator.facts.Monster;
import com.sbnz.crcalculator.facts.Action;
import com.sbnz.crcalculator.facts.Attack;
import com.sbnz.crcalculator.facts.AbilityName;
import com.sbnz.crcalculator.facts.AttackType;

rule "Determine strength damage bonus"

    when
        $m: Monster($actions: actions, strength.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.STRENGTH, damageBonus == null) from $attacks
    then
        System.out.println("Determine strength damage bonus fired");
        $attack.setDamageBonus($m.getStrength().getAbilityModifier());
        modify ($m) { setActions($actions) };
        
end

rule "Determine dexterity damage bonus"

    when
        $m: Monster($actions: actions, dexterity.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.DEXTERITY, damageBonus == null) from $attacks
    then
        System.out.println("Determine dexterity damage bonus fired");
        $attack.setDamageBonus($m.getDexterity().getAbilityModifier());
        modify ($m) { setActions($actions) };

end

rule "Determine intelligence damage bonus"

    when
        $m: Monster($actions: actions, intelligence.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.INTELLIGENCE, damageBonus == null) from $attacks
    then
        System.out.println("Determine intelligence damage bonus fired");
        $attack.setDamageBonus(0);
        modify ($m) { setActions($actions) };

end

rule "Determine wisdom damage bonus"

    when
        $m: Monster($actions: actions, wisdom.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.WISDOM, damageBonus == null) from $attacks
    then
        System.out.println("Determine wisdom damage bonus fired");
        $attack.setDamageBonus(0);
        modify ($m) { setActions($actions) };

end

rule "Determine charisma damage bonus"

    when
        $m: Monster($actions: actions, charisma.abilityModifier != null)
        Action($attacks: attacks) from $actions
        $attack: Attack(relevantAbility == AbilityName.CHARISMA, damageBonus == null) from $attacks
    then
        System.out.println("Determine charisma damage bonus fired");
        $attack.setDamageBonus(0);
        modify ($m) { setActions($actions) };

end